
import React from 'react';
import { Button } from '@/components/ui/button';
import { CheckCircle, ArrowRight, Zap, Clock, Shield } from 'lucide-react';

interface LandingCTAProps {
  onStartDemo: () => void;
  user: any;
}

const LandingCTA = ({ onStartDemo, user }: LandingCTAProps) => {
  const guarantees = [
    { icon: Zap, text: "Business registered in 48-72 hours or money back" },
    { icon: Shield, text: "100% compliance guarantee - we handle all violations" },
    { icon: Clock, text: "24/7 expert support included in all plans" }
  ];

  const urgencyStats = [
    "15,847 businesses launched this year",
    "₦2.5B+ in revenue generated by our users",
    "Average 67% revenue growth in first 6 months"
  ];

  return (
    <section className="py-20 bg-gradient-to-br from-blue-900 via-blue-800 to-emerald-600 relative overflow-hidden">
      {/* Background Pattern */}
      <div className="absolute inset-0 opacity-10">
        <div className="absolute top-10 left-10 w-32 h-32 bg-white rounded-full"></div>
        <div className="absolute bottom-20 right-20 w-24 h-24 bg-emerald-300 rounded-full"></div>
        <div className="absolute top-1/2 left-1/4 w-16 h-16 bg-blue-300 rounded-full"></div>
      </div>

      <div className="max-w-6xl mx-auto text-center px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Urgency Banner */}
        <div className="inline-flex items-center bg-emerald-500 text-white px-6 py-3 rounded-full text-sm font-semibold mb-8 animate-pulse">
          🔥 Limited Time: 50% Off Setup Fees This Month
        </div>

        <h2 className="text-4xl lg:text-6xl font-bold text-white mb-6 leading-tight">
          Ready to Join Nigeria's 
          <span className="text-emerald-300 block">Fastest-Growing Businesses?</span>
        </h2>
        
        <p className="text-xl lg:text-2xl text-blue-100 mb-8 max-w-4xl mx-auto leading-relaxed">
          Join 15,000+ Nigerian entrepreneurs who've transformed their ideas into thriving, compliant businesses with BizCore. 
          <strong className="text-white"> Start your journey today and be operational by week's end.</strong>
        </p>

        {/* Stats Bar */}
        <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-6 mb-10 border border-white/20">
          <div className="grid md:grid-cols-3 gap-6 text-center">
            {urgencyStats.map((stat, index) => (
              <div key={index} className="text-white">
                <div className="text-2xl font-bold mb-1">✨</div>
                <div className="text-sm font-medium">{stat}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Main CTA */}
        <div className="mb-10">
          <Button 
            onClick={onStartDemo}
            className="bg-emerald-600 hover:bg-emerald-500 text-white px-12 py-6 rounded-2xl text-xl lg:text-2xl font-bold transition-all transform hover:scale-105 shadow-2xl"
          >
            {user ? 'Enter Your Dashboard →' : 'Start Your Business Journey →'}
            <ArrowRight className="ml-3" size={28} />
          </Button>
          
          <div className="mt-6">
            <p className="text-emerald-200 text-lg font-medium">
              30-day free trial • No credit card required • Setup starts immediately
            </p>
            <p className="text-blue-200 text-sm mt-2">
              Join today and get your business registered by Friday ⚡
            </p>
          </div>
        </div>

        {/* Guarantees */}
        <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-8 border border-white/20">
          <h3 className="text-2xl font-bold text-white mb-6">Our Ironclad Guarantees</h3>
          <div className="grid md:grid-cols-3 gap-6">
            {guarantees.map((guarantee, index) => (
              <div key={index} className="flex items-start gap-4 text-left">
                <guarantee.icon className="text-emerald-300 flex-shrink-0 mt-1" size={24} />
                <div>
                  <p className="text-white font-medium leading-relaxed">{guarantee.text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Social Proof Footer */}
        <div className="mt-12 pt-8 border-t border-white/20">
          <div className="flex flex-col md:flex-row items-center justify-center gap-8 text-blue-200">
            <div className="flex items-center gap-2">
              <div className="flex">
                {[...Array(5)].map((_, i) => (
                  <span key={i} className="text-yellow-400 text-xl">⭐</span>
                ))}
              </div>
              <span className="font-medium">4.9/5 from 3,200+ reviews</span>
            </div>
            <div className="hidden md:block w-px h-6 bg-white/30"></div>
            <div className="font-medium">Featured in TechCrunch Nigeria & BusinessDay</div>
            <div className="hidden md:block w-px h-6 bg-white/30"></div>
            <div className="font-medium">SOC 2 Compliant • Bank-level security</div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LandingCTA;
